solution
mate-academy/react_movies-list-fetch-movies pull request #119
Opened 2020-11-12 11:12 UTC by Atteroot

[DEMO LINK](https://Atteroot.github.io/react_movies-list-fetch-movies/)

2020-11-16 13:30 UTC, Andrii1996 approved these changes

2020-11-19 09:10 UTC, danheim requested changes
Great start

2020-11-19 09:10 UTC, danheim commented on src/components/FindMovie/FindMovie.js
> +  };
async await

2020-11-19 09:10 UTC, danheim commented on src/components/FindMovie/FindMovie.js
> +  }).isRequired).isRequired,
Create shape for movie

2020-11-27 11:47 UTC, Vladimir-Beliy approved these changes

2020-12-09 10:51 UTC, Vladimir-Beliy requested changes
/

2020-12-09 10:52 UTC, Vladimir-Beliy approved these changes

2021-03-23 18:54 UTC, closed without merging