Develop
mate-academy/react_movies-list-fetch-movies pull request #294
Opened 2021-08-08 13:44 UTC by gponomarenko

[DEMO LINK](https://gponomarenko.github.io/react_dynamic-list-of-todos/)

2021-08-10 10:18 UTC, stasianich reviewed
Не работает поиск фильмов, вываливаются ошибки...

2021-08-10 10:18 UTC, stasianich commented on src/App.js
> +      if (!movies.some(movie => movie.imdbId === newMovie.imdbId)) {
&&

2021-08-10 10:18 UTC, stasianich commented on src/components/FindMovie/FindMovie.js
> +              className={`input ${isMovieFound ? 'is-danger' : ''} `}
classNames будет более элегантно  смотреться

2021-08-11 11:43 UTC, aionova requested changes

2021-08-11 11:43 UTC, aionova commented on src/components/FindMovie/FindMovie.js
> +              className={`input ${isMovieFound ? 'is-danger' : ''} `}
согласна. используй classNames

2021-08-11 11:43 UTC, aionova commented on src/components/FindMovie/FindMovie.js
> +              onClick={() => showFoundMovie()}
```suggestion
              onClick={showFoundMovie}
```

2021-08-11 11:43 UTC, aionova commented on src/components/FindMovie/FindMovie.js
> +              onClick={() => addMovie()}
```suggestion
              onClick={addMovie}
```

2021-08-11 11:43 UTC, aionova commented on src/components/FindMovie/FindMovie.js
> +          && (<MovieCard {...movie} />)
```suggestion
        {movie && (<MovieCard {...movie} />)
```

2021-08-11 11:43 UTC, aionova commented on src/components/FindMovie/FindMovie.js
> +          && (<MovieCard {...movie} />)
передавай movie явно, не используй spread

2021-08-11 11:43 UTC, aionova commented on src/App.js
> +      if (!movies.some(movie => movie.imdbId === newMovie.imdbId)) {
согласна

2021-08-12 10:58 UTC, gponomarenko commented
Дякую за коментарі та зауваження! Все врахую та викладу оновлення.

2021-08-16 18:08 UTC, gponomarenko commented on src/components/FindMovie/FindMovie.js
> +              className={`input ${isMovieFound ? 'is-danger' : ''} `}
+

2021-08-16 18:09 UTC, gponomarenko commented on src/App.js
> +      if (!movies.some(movie => movie.imdbId === newMovie.imdbId)) {
➕

2021-08-16 18:12 UTC, gponomarenko commented on src/components/FindMovie/FindMovie.js
> +              onClick={() => showFoundMovie()}
➕

2021-08-16 18:21 UTC, gponomarenko commented on src/components/FindMovie/FindMovie.js
> +          && (<MovieCard {...movie} />)
передав кожну пропсу ))

2021-08-16 18:24 UTC, gponomarenko commented
Все виправив! Додав новий апі-ключ

2023-11-06 14:35 UTC, closed without merging