solution
mate-academy/react_movies-list-fetch-movies pull request #458
Opened 2022-01-25 16:57 UTC by E-Sharpilo

[DEMO LINK](https://E-Sharpilo.github.io/react_movies-list-fetch-movies/)

2022-01-26 14:06 UTC, aliceblunt8 requested changes

2022-01-26 14:06 UTC, aliceblunt8 commented on src/components/FindMovie/FindMovie.tsx
> +  const [isMovieFind, setFindCheck] = useState(true);
```suggestion
  const [isMovieFound, setIsMovieFound] = useState(false);
```

2022-01-26 14:06 UTC, aliceblunt8 commented on src/components/FindMovie/FindMovie.tsx
> +              onClick={() => movie && addMovieToList(movie)}
check inside addMovieToList

```suggestion
              onClick={() => addMovieToList(movie)}
```

2022-01-26 14:06 UTC, aliceblunt8 commented on src/components/FindMovie/FindMovie.tsx
> +        {movie && <MovieCard movie={movie} />}
combine

2022-01-27 14:56 UTC, danylo-onishchuk approved these changes

2024-12-28 14:44 UTC, closed without merging