solution
mate-academy/react_movies-list-fetch-movies pull request #566
Opened 2022-05-23 11:57 UTC by misha200119

[DEMO LINK](https://misha200119.github.io/react_movies-list-fetch-movies/)

2022-05-24 07:27 UTC, yaremenko-maksym requested changes
<img width="192" alt="image" src="https://user-images.githubusercontent.com/99096412/169972132-fdf44912-0dbc-4165-85fa-0ec680d716c5.png">
<img width="189" alt="image" src="https://user-images.githubusercontent.com/99096412/169972335-16fcccc4-1a8c-4f8e-92a6-ecea35a41da9.png">

Пропускает пустой инпут, хорошо бы проверку на empty и на спец символы в строке.
После добавления в список, сбрасывай фильтр.

2022-05-24 07:27 UTC, yaremenko-maksym commented on src/components/FindMovie/FindMovie.tsx
> +              className="button is-light"
используй is-light и is-primary, чтобы показать, какие кнопки сейчас активны. Если нету превью, то кнопка добавления должна быть серой и т.д.

2022-05-24 09:01 UTC, misha200119 commented
> т, хорошо бы проверку на empty и

оно не пропускает пустые символы, просит ввести валидное значение, название тоже может состоять из спецсимволов

2022-05-25 17:54 UTC, AlinaMatuschak approved these changes

2022-05-25 17:54 UTC, AlinaMatuschak commented on src/components/FindMovie/FindMovie.tsx
> +      ) !== undefined) {
Object converts to true 

```suggestion
      if (prevValue.find(
        film => film.imdbID === findedMovie.imdbID,
      )) {
```

2025-08-10 13:04 UTC, closed without merging