Develop
mate-academy/react_movies-list-fetch-movies pull request #575
Opened 2022-05-25 09:21 UTC by kkiirill

[DEMO LINK](https://kkiirill.github.io/react_movies-list-fetch-movies/)

2022-05-25 14:42 UTC, SeKaM0 approved these changes
Great job

2022-05-25 15:22 UTC, HelenPetrovska approved these changes
Great!

2022-05-25 15:22 UTC, HelenPetrovska commented on src/App.tsx
> +    }
alert))

2022-05-25 15:22 UTC, HelenPetrovska commented on src/components/FindMovie/FindMovie.tsx
> +              })}
you can create method

2022-05-30 08:23 UTC, danylo-onishchuk requested changes

2022-05-30 08:23 UTC, danylo-onishchuk commented on src/App.tsx
> +    }
no alert

2022-05-30 08:23 UTC, danylo-onishchuk commented on src/api.ts
> +  const response = await fetch(`https://www.omdbapi.com/?apikey=9e088334&t=${title}`);
creare variable for url and api key

2022-05-30 11:51 UTC, danylo-onishchuk approved these changes

2023-01-03 18:22 UTC, closed without merging