solution
mate-academy/react_movies-list-fetch-movies pull request #616
Opened 2022-06-17 20:35 UTC by ZUBOV-ILLIA

[DEMO LINK](https://ZUBOV-ILLIA.github.io/react_movies-list-fetch-movies/)

2022-06-17 21:02 UTC, yelnikov-andrii approved these changes

2022-06-20 11:58 UTC, Denchepornyuk requested changes

2022-06-21 06:18 UTC, ZUBOV-ILLIA commented
> 

I did it intentionally, because I thought that if the field is empty, then there is no point in displaying an error)
Fixed
![image](https://user-images.githubusercontent.com/63620508/174729458-461574ab-6a80-4b52-8b8a-0385179c4781.png)

2022-06-23 09:43 UTC, Denchepornyuk approved these changes

2025-03-11 09:44 UTC, closed without merging