Initial solution
mate-academy/react_movies-list-fetch-movies pull request #766
Opened 2022-08-29 08:45 UTC by DashaPoliazz

[DEMO LINK](https://DashaPoliazz.github.io/react_movies-list-fetch-movies/)

2022-08-31 08:26 UTC, solaryasha requested changes

2022-08-31 08:26 UTC, solaryasha commented on src/App.tsx
> +    }) ? true : false;
use method `some` instead

2022-08-31 08:26 UTC, solaryasha commented on src/App.tsx
> +  const addMovie = (movieToAdd: Movie) => {
Use `useCallback` for rendering optimization

2022-08-31 08:26 UTC, solaryasha commented on src/components/FindMovie/FindMovie.tsx
> +export const FindMovie: React.FC<Props> = ({ addMovie }) => {
use React.memo

2022-08-31 08:26 UTC, solaryasha commented on src/components/FindMovie/FindMovie.tsx
> +      .then(res => {
```suggestion
      .then(response => {
```

2022-09-01 08:07 UTC, VETALEK requested changes
GJ 🔥 
use HTTPS 😉

2022-09-01 08:07 UTC, VETALEK commented on src/api.ts
> +const API_URL = 'http://www.omdbapi.com/?i=tt3896198&apikey=81ae11e5';
```suggestion
const API_URL = 'https://www.omdbapi.com/?i=tt3896198&apikey=81ae11e5';
```
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/55802630/187864617-9f549202-9a2f-4747-906c-1c54a2e34ffa.png">

2022-09-01 12:48 UTC, closed without merging