solution fetch movies
mate-academy/react_movies-list-fetch-movies pull request #825
Opened 2022-11-04 19:39 UTC by vladyslav-harkusha

[DEMO LINK](https://vladyslav-harkusha.github.io/react_movies-list-fetch-movies/)

2022-11-07 14:36 UTC, Anna-Borodaienko approved these changes

2022-11-16 14:21 UTC, Anna-Tkachenko requested changes

2022-11-16 14:21 UTC, Anna-Tkachenko commented on src/api.ts
> +  const apiKey = 'd049b4a';
will be better to move constant outside of the function

2022-11-16 14:21 UTC, Anna-Tkachenko commented on src/components/FindMovie/FindMovie.tsx
> +      addMovie([...movies, movie]);
function addMovie should accept only one movie, not the array with all movies

2022-11-16 14:21 UTC, Anna-Tkachenko commented on src/App.tsx
> +        <FindMovie movies={movies} addMovie={setMovies} />
create separate handler for addMovie function, it shouldn't be setMovies one

2022-11-17 14:38 UTC, Anna-Tkachenko approved these changes
Good job! 🔥

2024-10-30 19:03 UTC, closed without merging