solution
mate-academy/react_movies-list-fetch-movies pull request #885
Opened 2023-01-18 17:31 UTC by official-artem

[DEMO LINK](https://official-artem.github.io/react_movies-list-fetch-movies/)

2023-01-19 07:43 UTC, Nazar-Brunarskyi approved these changes
well done)

2023-01-19 09:56 UTC, valerii-derkach requested changes

2023-01-19 09:56 UTC, valerii-derkach commented on src/components/FindMovie/FindMovie.tsx
> +          })
lets use `try/catch/finally` here instead of `if/else` statement

2023-01-19 09:56 UTC, valerii-derkach commented on src/components/FindMovie/FindMovie.tsx
> +    };
let's move this method to parent component and pass it here as props

and do not forget to display an error when the film is already in the list

2023-01-19 09:56 UTC, valerii-derkach commented on src/components/FindMovie/FindMovie.tsx
> +          }}
move event.preventDefault() inside handleClickSubmit()

2023-01-19 15:09 UTC, valerii-derkach requested changes
add render optimization where it is needed

2023-01-19 15:09 UTC, valerii-derkach commented on src/App.tsx
> +  // const [array, setArray] = useState<MovieData | ResponseError>();
remove comments

2023-01-19 15:09 UTC, valerii-derkach commented on src/App.tsx
> +  const onAddMovie = (movie: Movie) => {
useCallback?

2023-01-19 15:09 UTC, valerii-derkach commented on src/App.tsx
> +    window.console.log(errorAddExist);
🤔

2023-01-19 15:09 UTC, valerii-derkach commented on src/components/FindMovie/FindMovie.tsx
> +                })}
move logic out of here - either create a method or combine somehow

2023-01-19 15:09 UTC, valerii-derkach commented on src/components/FindMovie/FindMovie.tsx
> +            {(isError || errorAddMovie) && (
create a variable

2023-01-19 15:09 UTC, valerii-derkach commented on src/components/FindMovie/FindMovie.tsx
> +                  window.console.log(movie);
console log

2023-01-19 15:09 UTC, valerii-derkach commented on src/components/FindMovie/FindMovie.tsx
> +                    clear();
move logic out of here - either create a method or combine somehow

2023-01-20 08:46 UTC, valerii-derkach approved these changes

2023-01-20 08:46 UTC, valerii-derkach commented on src/components/FindMovie/FindMovie.tsx
> +    const [isError, setIsError] = useState(false);
```suggestion
    const [isError, setError] = useState(false);
```

in boolean state it is ok to omit the prefix `is` and `should` it setState function 😉

2026-03-01 23:24 UTC, closed without merging