Solution
mate-academy/react_movies-list-fetch-movies pull request #908
Opened 2023-02-14 20:37 UTC by vlad-boikov

[DEMO LINK](https://vlad-boikov.github.io/react_movies-list-fetch-movies/)

2023-02-15 09:11 UTC, tetiana-ivanchenko requested changes

2023-02-15 09:11 UTC, tetiana-ivanchenko commented on src/components/FindMovie/FindMovie.tsx
> +  const [error, setError] = useState(false);
```suggestion
  const [isError, setIsError] = useState(false);
```

2023-02-15 09:11 UTC, tetiana-ivanchenko commented on src/components/FindMovie/FindMovie.tsx
> +                }}
move it to the separate function

2023-02-15 18:56 UTC, SanyaBratashchuk requested changes

2023-02-15 18:56 UTC, SanyaBratashchuk commented on src/App.tsx
> +    setMovies([...movies, movie]);
```suggestion
    setMovies(prevMovies => [...prevMovies, movie]);
```

2023-02-15 18:56 UTC, SanyaBratashchuk commented on src/components/FindMovie/FindMovie.tsx
> +  }, [movie]);
Why do you need useCallback here?

2023-02-17 10:33 UTC, OleziO approved these changes

2023-02-17 10:39 UTC, OleziO approved these changes

2023-02-17 10:39 UTC, OleziO commented on src/components/FindMovie/FindMovie.tsx
> +  const [isError, setError] = useState(false);
`[isError, setError]` > `[isError, setIsError]`

2025-02-28 07:41 UTC, closed without merging